

    <div class="regex_def">

        A regular expression is a special text string for describing a search pattern. You can think of regular expressions as wildcards on steroids.
    </div>

    <br/>
    <div class="regex_help_text">


        Copy & Paste One of the below RegEx Patterns OR Enter your own pattern in "Enter RegEx Pattern" field.    
    </div>
    <br/>
    <h3>Popular RegEx Patterns</h3>
    