<table class="table widefat">

    <thead>
        <tr>
            <td>Field</td>
            <td>RegEx Pattern</td>
            <td>Condition</td>

        </tr>
    </thead>
    <tbody>


        <tr>
            <td>
                Address Line 1
            </td>
            <td>
                [a-zA-Z\d\s\-\,\#\.\+]+
            </td>
            <td>
                Validate Postal address
            </td>
        </tr>
        <tr>
            <td>
                Address Line 2
            </td>
            <td>
                [a-zA-Z\d\s\-\,\#\.\+]+
            </td>
            <td>
                Validate Postal address
            </td>
        </tr>
        <tr>
            <td>
                City
            </td>
            <td>
                [a-zA-Z\d\s\-\,\#\.\+]+
            </td>
            <td>
                Validate City
            </td>
        </tr>
        <tr>
            <td>
                State
            </td>
            <td>
                [a-zA-Z\d\s\-\,\#\.\+]+
            </td>
            <td>
                Validate State
            </td>
        </tr>
        <tr>
            <td>
                ZIP
            </td>
            <td>
                ^\d{5,6}(?:[-\s]\d{4})?$
            </td>
            <td>
                Validate ZIP code
            </td>
        </tr>



    </tbody>
</table>