<table class="table widefat">

    <thead>
        <tr>
            <td>Field</td>
            <td>RegEx Pattern</td>
            <td>Condition</td>
            
        </tr>
    </thead>
    <tbody>

        <tr>
            <td>
                Website
            </td>
            <td>
                 https?\:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,}
            </td>
            <td>
              Validates correct URL
            </td>
        </tr>


    </tbody>
</table>

