<table class="table widefat">

    <thead>
        <tr>
            <td>Field</td>
             <td>RegEx Pattern</td>
            <td>Condition</td>
           
        </tr>
    </thead>
    <tbody>
        
         <tr>
                <td>
                    First name
                </td>
                <td>
                    ^[a-z\s]+$
                </td>
                <td>
                   Validates Character and spaces
                </td>
            </tr>
            
             <tr>
                <td>
                  Middle Name
                </td>
                <td>
                    ^[a-z\s]+$
                </td>
                <td>
                    Validates Character and spaces
                </td>
            </tr>
            
            
             <tr>
                <td>
                    Last Name
                </td>
                <td>
                    ^[a-z\s]+$
                </td>
                <td>
                    Validates Character and spaces
                </td>
            </tr>
        
        
    </tbody>
</table>