<table class="table widefat">

    <thead>
        <tr>
            <td>Field</td>
            <td>RegEx Pattern</td>
            <td>Condition</td>
            
        </tr>
    </thead>
    <tbody>


        <tr>
            <td> Hour </td>
            
            <td>
                ^(1[0-2]|[1-9])$
            </td>
            <td>
                Validates range of 1-12 (hour)
            </td>
        </tr>
        <tr>
            <td> Minutes </td>
          
            <td>
                ^[1-5]?[0-9]$
            </td>
              <td>
                Validates range of 1-59 (hour): 
            </td>
        </tr>







    </tbody>
</table>