<table class="table widefat">

    <thead>
        <tr>
            <td>Field</td>
             <td>RegEx Pattern</td>
            <td>Condition</td>
           
        </tr>
    </thead>
    <tbody>

        <tr>
            <td>
               Number
            </td>
            <td>
                ^[0-9]*$
            </td>
            <td>
                Validate Numericality 
            </td>
        </tr>


      


    </tbody>
</table>