<table class="table widefat">

    <thead>
        <tr>
            <td>Field</td>

            <td>RegEx Pattern</td>
            <td>Condition</td>

        </tr>
    </thead>
    <tbody>

        <tr>
            <td>
                Textarea
            </td>
            <td>
                ^[\s0-9A-Za-z!@.,;:'"?-]{1,140}$
            </td>
            <td>
                Validate character limit to 140 
            </td>
        </tr>


        </tr


    </tbody>
</table>