<table class="table widefat">

    <thead>
        <tr>
            <td>Field</td>
            <td>RegEx Pattern</td>
            <td>Condition</td>

        </tr>
    </thead>
    <tbody>

        <tr>
            <td>
                Phone
            </td>
            <td>
                ^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$
            </td>
            <td>
                Validate Phone number  
            </td>
        </tr>


        </tr


    </tbody>
</table>