<div class="how_to">
<div class="col-left-video"><h2><i class="fa fa-hand-o-right" aria-hidden="true"></i> Watch This Video</h2>

<iframe width="100%" height="315" src="https://www.youtube.com/embed/m_bv3eCmvgs" frameborder="0" allowfullscreen></iframe>
</div>
<div class="col-left-content">
<h2><i class="fa fa-hand-o-right" aria-hidden="true"></i> Read The Instructions</h2>
	<div class="content-internal">
    
    <ol>
             <li>Install "Real Time Validation For Gravity Form" Plugin.
             <div class="step_img"><img src="<?php echo LV_ROOT_URL."admin/assets/img/1.jpg"; ?>" width="960" height="720" /></div>
             </li>
            <li>Activate the Plugin.
             <div class="step_img"><img src="<?php echo LV_ROOT_URL."admin/assets/img/2.jpg"; ?>" width="960" height="720" /></div>
            </li>
            <li>Go to Forms -> Individual Form Settings -> Real Time Validation. Enable Real Time Validation by toggling switch to "Yes" and Save the Settings.
            <div class="step_img"><img src="<?php echo LV_ROOT_URL."admin/assets/img/3.jpg"; ?>" width="960" height="720" /></div>
            </li>
            <li>Go to Form Editor and Expand Any Field options. In General Tab under Rules section Check 'Required" option to make the field required. Skip this step if field is not required.
            <div class="step_img"><img src="<?php echo LV_ROOT_URL."admin/assets/img/4.jpg"; ?>" width="960" height="720" /></div>
            </li>
             <li>Go to Appearance Tab -> Custom Validation Message Section & if need be Override Default Validation Message.
           <div class="step_img"><img src="<?php echo LV_ROOT_URL."admin/assets/img/5.jpg"; ?>" width="960" height="720" /></div> 
           </li>
            <li>Go to Advanced Tab -> Check the option "Validate Real Time Input".
            <div class="step_img"><img src="<?php echo LV_ROOT_URL."admin/assets/img/6.jpg"; ?>" width="960" height="720" /></div>
            </li>
           
           
            <li>Under field "Enter RegEx Pattern" , Enter Your Own RegEx Pattern or Copy N Paste Popular RegEx Patterns from our available patterns list.
            <div class="step_img"><img src="<?php echo LV_ROOT_URL."admin/assets/img/7.jpg"; ?>" width="960" height="720" /><br /><br />
            </div>
				 </li>
		
			<li>Here is list of Popular RegEx Patterns from our available patterns list.
            <div class="step_img">
			<img src="<?php echo LV_ROOT_URL."admin/assets/img/8.jpg"; ?>" width="960" height="720" />

</div>
            </li>
           
            <li>Sample RegEx pattern entered here.
            <div class="step_img"><img src="<?php echo LV_ROOT_URL."admin/assets/img/9.jpg"; ?>" width="960" height="720" /></div>
            </li>
            <li>Customize the Real Time Error Message to display above/ below the form field. 
            <div class="step_img"><img src="<?php echo LV_ROOT_URL."admin/assets/img/10.jpg"; ?>" width="960" height="720" /></div>
            </li>
            
            
            <li>Update form to have Real Time Validation feature activated in front end Gravity form.
            <div class="step_img"><img src="<?php echo LV_ROOT_URL."admin/assets/img/11.jpg"; ?>" width="960" height="720" /></div>
            </li>

    </ol>
    </div>

</div>
</div>
