<div class="pro-main">
    <h2 class="centered">Real Time Validation is supported by XLPlugins.<br/> Checkout our more plugins.</h2>
    <div class="xl-upsells">



        <div class="postbox xl-cell " style="background-color: #9164b5">
            <a href="https://xlplugins.com/woocommerce-sales-triggers/?utm_source=rtv&amp;utm_medium=sidebar&amp;utm_campaign=other-products&amp;utm_term=sales-trigger" target="_blank"></a>
            <img src="http://35.193.52.20/wp-content/plugins/finale-woocommerce-sales-countdown-timer-discount/admin/assets/img/sales-trigger.png">
            <div class="xl-cell-head">XL WooCommerce Sales Triggers</div>
            <div class="xl-cell-desc" >Use 7 Built-in Sales Triggers to Optimise Single Product Pages For More Conversions</div>
        </div>



        <div class="postbox xl-cell" style="background-color: #1bc2a8">
            <a href="https://xlplugins.com/woocommerce-thank-you-page-nextmove/?utm_source=rtv&amp;utm_medium=sidebar&amp;utm_campaign=other-products&amp;utm_term=nextmove" target="_blank"></a>
            <img src="http://35.193.52.20/wp-content/plugins/finale-woocommerce-sales-countdown-timer-discount/admin/assets/img/nextmove.png">
            <div class="xl-cell-head">NextMove WooCommerce Thank You Pages</div>
            <div class="xl-cell-desc">Get More Repeat Orders With 17 Plug n Play Components</div>
        </div>

        <div class="postbox xl-cell"  style="background-color: #fd7e21">
            <a href="https://xlplugins.com/finale-woocommerce-sales-countdown-timer-discount-plugin/?utm_source=rtv&amp;utm_medium=sidebar&amp;utm_campaign=other-products&amp;utm_term=finale" target="_blank"></a>
            <img src="http://35.193.52.20/wp-content/plugins/woo-thank-you-page-nextmove-lite/admin/assets/img/finale.png">
            <div class="xl-cell-head">Finale WooCommerce Sales Countdown Timer</div>
            <div class="xl-cell-desc">Run Urgency Marketing Campaigns On Your Store And Move Buyers to Make A Purchase</div>
        </div>    



    </div>
</div>